spring:
  application:
  name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true